function fg = greenwood_frequency(wavelength, ...
                                  zenith_angle, ...
                                  satellite_altitude, ...
                                  ghv_args, ...
                                  bfw_args)

    fun = @(x) generalised_hufnagel_valley(ghv_args, x) .* ...
                (bufton_wind_model(x, bfw_args) .^ (5/3));
    result = integral(@(x) fun(x), 0, satellite_altitude);

    fg = 2.31 .* (wavelength ^ (-6/5)) .* ((...
                sec(zenith_angle) .* result) .^ (3/5));
end
