function eta_link = link_efficiency_adaptive_optics(rx_opt_trans, ...
                                                    tx_opt_trans, ...
                                                    atmos_opt_trans, ...
                                                    obs_angle, ...
                                                    rx_apt_dia, ...
                                                    I_diffraction, ...
                                                    I_short_term, ...
                                                    waist_diffraction, ...
                                                    waist_short_term, ...
                                                    strehl)
    
    a = rx_opt_trans .* tx_opt_trans .* (atmos_opt_trans .^ sec(obs_angle));
    b = (rx_apt_dia ^ 2) / 2;
    c = (I_diffraction .* strehl) ./ (waist_diffraction .^ 2);
    d = (I_short_term .* (1 - strehl)) ./ (waist_short_term .^ 2);
    e = a .* b .* (c + d);
    eta_link = 10 .* log10(e);
end
