function eta_link = link_efficiency(rx_opt_trans, ...
                                    tx_opt_trans, ...
                                    atmos_opt_trans, ...
                                    obs_angle, ...
                                    rx_apt_dia, ...
                                    spot_rad, ...
                                    beam_wander)

    a = rx_opt_trans * tx_opt_trans .* (atmos_opt_trans .^ sec(obs_angle));
    b = (rx_apt_dia ^ 2) ./ (2 * ((spot_rad) .^ 2));
    c = a .* b .* beam_wander;

    eta_link = 10 .* log10(c);
end
