function zeta = phase_anisoplanatic_error(zenith_angles, ...
                                          wavenumber, ...
                                          satellite_altitude, ...
                                          ghv_args, ...
                                          delta_tilt)

        theta = isoplanatic_angle(zenith_angles, ...
                                   wavenumber, ...
                                   satellite_altitude, ...
                                   ghv_args);

        zeta = (delta_tilt ./ theta) .^ (5/6);
end
