function freq = tracking_frequency(tx_diameter, ...
                                   wavelength, ...
                                   zenith_angle, ...
                                   satellite_altitude, ...
                                   bfw_args, ...
                                   ghv_args)

    fun = @(x) (generalised_hufnagel_valley(ghv_args, x) ...
                    .* (bufton_wind_model(x, bfw_args).^2));

    result = integral(@(x) fun(x), 0, satellite_altitude);

    freq = ( ...
            0.331 .* (tx_diameter ^ (-1/6)) .* (wavelength .^ (-1)) ...
            .* ((sec(zenith_angle) .* result) .^ (1/2)) ...
            );
end

