function [Secret_Key_Rate,QBER,Sifted_Key_Rate] = CV_model(Source,...
                                                prob_dark_counts,...
                                                loss_dB,...
                                                protocol_efficiency,...
                                                Detector) %#ok<*INUSD> 
%for now, this is a null function which returns zeros of the correct dimensions


Output_Dimensions = size(loss_dB);

Secret_Key_Rate = zeros(Output_Dimensions);
QBER = nan(Output_Dimensions);
Sifted_Key_Rate = zeros(Output_Dimensions);