classdef qkd_protocols

    enumeration
        BB84, DecoyBB84, E91, COW, DPS
    end

    methods

        function [req_source, req_detector, efficiency] = requirements(proto)
            req_source = {};
            req_detector = {};
            efficiency = 1;

            switch proto
                case qkd_protocols.BB84
                    req_source = { ...
                        'g2', 'Mean_Photon_Number', 'State_Prep_Error' ...
                        };
                    req_detector = { ...
                        'Dark_Count_Rate','Time_Gate_Width','Dead_Time' ...
                        };
                    efficiency = 0.5;

                case qkd_protocols.DecoyBB84
                    req_source = { ...
                            'Mean_Photon_Number', ...
                            'State_Prep_Error', ...
                            'State_Probabilities' ...
                        };
                    req_detector = { ...
                        'Dark_Count_Rate','Time_Gate_Width','Dead_Time' ...
                        };
                    efficiency = 0.5;

                case qkd_protocols.E91
                    req_source = { ...
                        'g2', 'Mean_Photon_Number', 'State_Prep_Error' ...
                        };
                    req_detector = { ...
                        'Dark_Count_Rate','Time_Gate_Width','Dead_Time' ...
                        };
                    efficiency = 1;

                case qkd_protocols.COW
                    req_source = { ...
                        'State_Probabilities', ...
                        'Mean_Photon_Number', ...
                        'State_Prep_Error'
                        };
                    req_detector = { ...
                        'Time_Gate_Width', 'Dead_Time', 'Visibility'
                        };
                    efficiency = 1;

                case qkd_protocols.DPS
                    req_source = { ...
                        'Mean_Photon_Number', ...
                        'State_Prep_Error', ...
                        'State_Probabilities' ...
                        };
                    req_detector = { ...
                        'Dark_Count_Rate', ...
                        'Time_Gate_Width', ...
                        'QBER_Jitter', ...
                        'Visibility'
                        };
                    efficiency = 1;

            end
        end

    end

end
