classdef DetectorPreset

    properties
        Name {mustBeText} = ''
        Dark_Count_Rate { ...
            mustBeNumeric, ...
            mustBeGreaterThanOrEqual(Dark_Count_Rate, 0)}
        Dead_Time {mustBeNumeric, mustBeGreaterThanOrEqual(Dead_Time, 0)}

        Jitter_Histogram { ...
            mustBeNumeric, ...
            mustBeGreaterThanOrEqual(Jitter_Histogram, 0)}
        Histogram_Bin_Width {mustBeNumeric, mustBePositive}

        Efficiencies_Wavelengths {mustBeNumeric}
        Efficiencies_Values { ...
            mustBeNumeric, ...
            mustBeGreaterThanOrEqual(Efficiencies_Values, 0) ...
            mustBeLessThanOrEqual(Efficiencies_Values, 1)}
    end

end
