%% Making some presets
clear all
close all
clc

%% Example usage to generate Hamamatsu detector
clear all
close all
clc

Efficiency_Data_Location = 'Hamamatsu_efficiency.mat';
eff = load(Efficiency_Data_Location);

Hamamatsu = detectorPresetBuilder;
Hamamatsu = Hamamatsu ...
    .addName('Hamamatsu') ...
    .addDarkCountRate(10) ...
    .addDeadTime(0) ...
    .addJitterHistogram(load('HamamatsuHistogram.mat').Counts, 10^-12) ...
    .addDetectorEfficiencyArray(eff.wavelengths, eff.efficiency) ...
    .makeDetectorPreset()


%% Example usage to generate Perkin Elmer detector
clear all
close all
clc

Efficiency_Data_Location = 'perkin_elmer_efficiency.mat';
eff = load(Efficiency_Data_Location);

Perkin_Elmer = detectorPresetBuilder;
Perkin_Elmer = Perkin_Elmer ...
    .addName('Perkin_Elmer') ...
    .addDarkCountRate(10) ...
    .addDeadTime(0) ...
    .addJitterHistogram(load('PerkinElmerHistogram.mat').Counts, 10^-12) ...
    .addDetectorEfficiencyArray(eff.wavelengths, eff.efficiency) ...
    .makeDetectorPreset()


%% Example usage to generate Excelitas detector
clear all
close all
clc

Efficiency_Data_Location = 'Excelitas_efficiency.mat'';
eff = load(Efficiency_Data_Location);

Excelitas = detectorPresetBuilder;
Excelitas = Excelitas ...
    .addName('Excelitas') ...
    .addDarkCountRate(10) ...
    .addDeadTime(0) ...
    .addJitterHistogram(load('ExcelitasHistogram.mat').Counts, 10^-12) ...
    .addDetectorEfficiencyArray(eff.wavelengths, eff.efficiency) ...
    .makeDetectorPreset()


%% Example usage to generate Micro Photon Devices detector
clear all
close all
clc

Efficiency_Data_Location = 'MPD_efficiency.mat';
eff = load(Efficiency_Data_Location);

MPD = detectorPresetBuilder;
MPD = MPD ...
    .addName('Micro Photon Devices') ...
    .addDarkCountRate(10) ...
    .addDeadTime(77e-9) ...
    .addJitterHistogram(load('MPDHistogram.mat').Counts, 10^-12) ...
    .addDetectorEfficiencyArray(eff.wavelengths, eff.efficiency) ...
    .makeDetectorPreset()


%% Example usage to generate Laser Components detector
clear all
close all
clc

Efficiency_Data_Location = 'LaserComponents_efficiency.mat';
eff = load(Efficiency_Data_Location);

LaserComp = detectorPresetBuilder;
LaserComp = LaserComp ...
    .addName('Laser Components') ...
    .addDarkCountRate(10) ...
    .addDeadTime(0) ...
    .addJitterHistogram(load('LaserComponentHistogram.mat').Counts, 10^-12) ...
    .addDetectorEfficiencyArray(eff.wavelengths, eff.efficiency) ...
    .makeDetectorPreset()
