%% test detector preset builder

clear all
close all
clc

a = linspace(0, 1, 3);
b = reshape(linspace(0, 0.9, 9), [3, 3]);
b = linspace(0, 0.9, 3);


Efficiency_Data_Location = 'Hamamatsu_efficiency.mat';
eff = load(Efficiency_Data_Location);

builder = detectorPresetBuilder;
builder = builder ...
    .addName("Hamamatsu") ...
    .addDarkCountRate(10) ...
    .addDeadTime(0) ...
    .addJitterHistogram(load('HamamatsuHistogram.mat').Counts, 10^-12) ...
    .addDetectorEfficiencyArray(eff.wavelengths, eff.efficiency) ...
    .makeDetectorPreset()
    %.preset

builder = detectorPresetBuilder;
builder = builder ...
    .addName("Hamamatsu") ...
    .addDarkCountRate(10) ...
    .addJitterHistogram(load('HamamatsuHistogram.mat').Counts, 10^-12) ...
    .addDetectorEfficiencyArray(eff.wavelengths, eff.efficiency) ...
    .makeDetectorPreset()
    %.preset

% b = linspace(0, 0.9, 9);
% sum(size(a) == size(b)) == 2
% builder = detectorPresetBuilder;
% builder = builder ...
%     .addDarkCountRate(1) ...
%     .addDeadTime(2) ...
%     .addDetectorEfficiencyArray(a, b) ...
%     .preset
