function GeoSat = GEOSat()
%% provide a default implemntation of a geosynchronous satellite which can have
%% its on-board details replaced

GEOSatTelescope = Telescope(0.1,'Wavelength',850,...
                                'Pointing_Jitter',1E-6);

GEOSatSource = Source(850,'Repetition_Rate',1E8);

GeoSat = Satellite(GEOSatTelescope,...
                'Source',GEOSatSource,...
                'Name','Geostationary Sat',...
                'semiMajorAxis',41264*1E3,...
                'eccentricity',0,...
                'inclination',0,...
                'rightAscensionOfAscendingNode',0,...
                'argumentOfPeriapsis',0,...
                'trueAnomaly',275,...
                'startTime',datetime(2000,1,1,0,0,0),...
                'stopTime',datetime(2000,1,8,0,0,0),...
                'sampleTime',seconds(1));