function SSSat = SunSynch15perDaySat()
%% provide a default implemntation of a sun synchronous satellite which can have
%% its on-board details replaced. This satellite makes exactly 15 orbits per day so passes the same ground points each day

SatTelescope = Telescope(0.1,'Wavelength',850,...
                                'Pointing_Jitter',1E-6);

SatSource = Source(850,'Repetition_Rate',1E8);

SSSat = Satellite(SatTelescope,...
                'Source',SatSource,...
                'Name','SunSynchronous Sat',...
                'semiMajorAxis',6945.025*1E3,...
                'eccentricity',0,...
                'inclination',97.309908,...
                'rightAscensionOfAscendingNode',-10,...
                'argumentOfPeriapsis',0,...
                'trueAnomaly',0,...
                'startTime',datetime(2000,1,1,0,0,0),...
                'stopTime',datetime(2000,1,14,0,0,0),...
                'sampleTime',seconds(1));