function TG2 = Tiangong2()
%% provide a default implemntation of a the orbit which Tiangong-2 (chinese space station)
% has so it can have its on-board details replaced. This is a MIO

SatTelescope = Telescope(0.1,'Wavelength',850,...
                                'Pointing_Jitter',1E-6);

SatSource = Source(850,'Repetition_Rate',1E8);

TG2 = Satellite(SatTelescope,...
                'Source',SatSource,...
                'Name','SunSynchronous Sat',...
                'semiMajorAxis',6658.6*1E3,...
                'eccentricity',0.0143359,...
                'inclination',42.7846,...
                'rightAscensionOfAscendingNode',135.0246,...
                'argumentOfPeriapsis',272.5645,...
                'trueAnomaly',218.4707,...
                'startTime',datetime(2000,1,1,0,0,0),...
                'stopTime',datetime(2000,1,8,0,0,0),...
                'sampleTime',seconds(30));