classdef output_user
    properties (SetAccess = protected)
        Label
    end
    methods
        function out = output_user(label)
            arguments (Repeating)
                label {mustBeMember(label, {                      ...
                    'lambda',   'wavenumber', 'sza',    'zout',     ...
                    'edir',     'eglo',       'edn',    'eup',      ...
                    'enet',     'esum',       'uu',     'fdir',     ...
                    'fglo',     'fdn',        'fup',    'f',        ...
                    'uavgdir',  'uavgglo',    'uavgdn', 'uavgup',   ...
                    'uavg',     'spher_alb',  'albedo', 'heat',     ...
                    'p',        'T',          'T_d',    'T_sur',    ...
                    'theta',    'theta_e',    'n_AIR',  'rho_AIR',  ...
                    'mmr_AIR',  'vmr_AIR',    'n_O3',   'rho_O3',   ...
                    'mmr_O3',   'vmr_O3',     'n_O2',   'rho_O2',   ...
                    'mmr_O2',   'vmr_O2',     'n_H20',  'rho_H20',  ...
                    'mmr_H20',  'vmr_H20',    'n_CO2',  'rho_CO2',  ...
                    'mmr_CO2',  'vmr_CO2',    'n_NO2',  'rho_NO2',  ...
                    'mmr_NO2',  'vmr_NO2',    'n_BRO',  'rho_BRO',  ...
                    'mmr_BRO',  'vmr_BRO',    'n_OCLO', 'rho_OCLO', ...
                    'mmr_OCLO', 'vmr_OCLO',   'n_HCHO', 'rho_HCHO', ...
                    'mmr_HCHO', 'vmr_HCHO',   'n_O4',   'rho_O4',   ...
                    'mmr_O4',   'vmr_O4'})}

            end
            out.Label = cellstr(label);
        end
    end
end
