function atm_turb_cor_len = atmospheric_turbulence_coherence_length( ...
                    wavenumber, zenith_angle, satellite_altitude, ghv_args)

    fun = @(x) (generalised_hufnagel_valley(ghv_args, x) ...
                    .* ((1 - (x ./ satellite_altitude)) .^ (5/3)));

    result = integral(@(x) fun(x), 0, satellite_altitude);

    atm_turb_cor_len = (0.423 ...
                        .* (wavenumber ^ 2) ...
                        .* sec(zenith_angle) ...
                        .* result) .^ (-3/5);
end
