function ca_errors = centroid_anisoplantism_errors(wavelength, ...
                                                   tx_diameter, ...
                                                   atmospheric_turbulence)

    ca_errors = ( ...
            (5.51e-2) ...
            .* (wavelength / tx_diameter) ...
            .* ((tx_diameter ./ atmospheric_turbulence) .^ (5 / 6)) ...
            );
end
