function zeta = fit_error(Zernike_polynomial, ...
                             transmitter_diameter, ...
                             atmospheric_turbulence)
    zeta_sq = (0.2944 * (Zernike_polynomial ^ (-sqrt(3)/2))) ...
              .* ((transmitter_diameter ./ atmospheric_turbulence) .^ (5/3));
    zeta = sqrt(zeta_sq);
end
