function width = long_term_gaussian_beam_width(beam_waist, ...
                                               L, ...
                                               rayleigh_range, ...
                                               wavenumber, ...
                                               atmospheric_turbulence)

    A = 1 + ((L.^2) / (rayleigh_range ^ 2));
    B = 2 * (((4.2 .* L) ./ (wavenumber .* atmospheric_turbulence)).^2);
    C = ((beam_waist.^2) .* A) + B;
    %C = (beam_waist .^ 2) .* A;
    width = sqrt(C);
    %width = sqrt((beam_waist .^ 2) .* (1 + ((L.^2) ./ (rayleigh_range .^ 2))));
end
