function width = short_term_gaussian_beam_width(beam_waist, ...
                                                L, ...
                                                rayleigh_range, ...
                                                wavenumber, ...
                                                atmospheric_turbulence)

    A = (beam_waist .^ 2) .* (1 + ((L .^ 2) / (rayleigh_range ^ 2)));
    B = (4.2 .* L) ./ (wavenumber .* atmospheric_turbulence);
    C = (atmospheric_turbulence ./ beam_waist) .^ (1 / 3);
    D = B .* (1 - (0.26 .* C));

    width = sqrt(A + (2 .* (D .^ 2)));
end
