function delay_error = tilt_feedback_delay_error(tracking_frequency, ...
                                                 correction_bandwidth, ...
                                                 wavelength, ...
                                                 tx_diameter)

    delay_error = ( ...
            (tracking_frequency ./ correction_bandwidth) ...
            .* (wavelength / tx_diameter) ...
            );
end
