classdef DetectorPreset

    properties
        Name {mustBeText} = ''
        Dark_Count_Rate { ...
            mustBeNumeric, ...
            mustBeGreaterThanOrEqual(Dark_Count_Rate, 0)}
        Dead_Time {mustBeNumeric, mustBeGreaterThanOrEqual(Dead_Time, 0)}

        Jitter_Histogram { ...
            mustBeNumeric, ...
            mustBeGreaterThanOrEqual(Jitter_Histogram, 0)}
        Histogram_Bin_Width {mustBeNumeric, mustBePositive}

        Wavelength_Range {mustBeNumeric}
        Efficiencies { ...
            mustBeNumeric, ...
            mustBeGreaterThanOrEqual(Efficiencies, 0) ...
            mustBeLessThanOrEqual(Efficiencies, 1)}
    end

end
