libRadTranPath = utilities.nativePathFrom('C:\Users\ccs2000\Documents\libRadtran-2.0.5\');
lrt = libradtran.libRadtran(libRadTranPath);

atm = lrt.GeneralAtmosphereSettings() ...
    .Atmosphere("Default", "tropics");

spec = lrt.SpectralSettings() ...
    .RadiationSource("solar", "File",  utilities.nativePathFrom([libRadTranPath,'data\solar_flux\kurudz_1.0nm.dat']));

alb = lrt.SurfaceSettings() ...
    .SurfaceAlbedo(0.02);

rte = lrt.SolverSettings() ...
    .Solver("mystic");

mc = lrt.MysticsSettings() ...
    .Photons(100000)...
    .Polarisation("(1) (1,1,0,0)")...
    .Backward()...
    .BackwardOutput("edir")...
    .Basename('C:\Users\ccs2000\Desktop\libRadtran_bin\mc_output.txt')...
    .Vroom("off")...
    .RadAlpha(10);

geo = lrt.GeometrySettings() ...
    .OutputPolarAngles(1:1:90, "Degrees")...
    .SolarAzimuthAngle(0)...
    .OutputAltitudes(0)...
    .Time(datetime("now"))...
    .SensorLatitude("N", 56.405)...
    .SensorLongitude("W", 3.183);

out = lrt.OutputSettings() ...
    .OutputColumns("lambda", "zout", "uu", "edir", "eglo", "edn", "eup", "enet", "esum")...
    .OutputQuantity("reflectivity")...
    .PostProcessing("per_nm")...
    .FileAndFormat("File", 'C:\Users\ccs2000\Desktop\libRadtran_bin\output.txt');

mol = lrt.MoleculeSettings()...
    .MolecularAbsorption("reptran coarse")...
    .CrossSectionModel("rayleigh_Bodhaine")...
    .ModifySpecies("O3", 200, "DU", "H2O", 20, "MM");

spec = lrt.SpectralSettings() ...
    .WavelengthRange(500, 950);

aer = lrt.AerosolSettings() ...
    .Season("Spring_Summer") ...
    .Default("on") ...
    .Visibility(50) ...
    .Species_file("continental_average");

config_string = lrt.StringFromConfiguration();
disp(char(config_string))

Output_file = RunConfiguration(lrt,'C:\Users\ccs2000\Desktop\libRadtran_bin\','libRadtran','Verbosity','Verbose');

data = ReadData(lrt);