clear all
clc
lrt = libRadtran();

atm = lrt.GetGeneralAtmosphereSettings() ...
    .Atmosphere("Default", "tropics");

spec = lrt.GetSpectralSettings() ...
    .RadiationSource("solar", "File",  "~/libRadtran-2.0.4/data/solar_flux/kurudz_1.0nm.dat");

alb = lrt.GetSurfaceSettings() ...
    .SurfaceAlbedo(0.02);

rte = lrt.GetSolverSettings() ...
    .Solver("mystic");

mc = lrt.GetMysticsSettings() ...
    .Photons(100000)...
    .Polarisation("(1) (1,1,0,0)")...
    .Backward()...
    .BackwardOutput("edir")...
    .Basename("~/Documents/MATLAB/lrt/lrt_new")...
    .Vroom("on")...
    .RadAlpha(10);

geo = lrt.GetGeometrySettings() ...
    .OutputPolarAngles(linspace(10, 90, 9), "Degrees")...
    .SolarAzimuthAngle(0)...
    .OutputAltitudes(0)...
    .Time(datetime("now"))...
    .SensorLatitude("N", 56.405)...
    .SensorLongitude("W", 3.183);

out = lrt.GetOutputSettings() ...
    .OutputColumns("lambda", "zout", "uu", "edir", "eglo", "edn", "eup", "enet", "esum")...
    .OutputQuantity("reflectivity")...
    .PostProcessing("per_nm")...
    .FileAndFormat("File", './spooky.txt');

mol = lrt.GetMoleculeSettings()...
    .MolecularAbsorption("reptran coarse")...
    .CrossSectionModel("rayleigh_Bodhaine")...
    .ModifySpecies("O3", 200, "DU", "H2O", 20, "MM");

spec = lrt.GetSpectralSettings() ...
    .WavelengthRange(500, 950);

aer = lrt.GetAerosolSettings() ...
    .Season("Spring_Summer") ...
    .Default("on") ...
    .Visibility(50);

config_string = lrt.ConfigString();
disp(char(config_string))
