classdef far_field_albedo < card

    properties

        spectral_reflectance;
        amount;
        details;

        tilt = 0;
        tilt_degree = 0;
        zonal_broadband_albedo;
        local_foreground_albedo;
        local_background_albedo;
        azimuth;


    end

    properties(Hidden=true)

        albedo_opts = {...
        'Fixed broadband albedo, —, Lambertian, 0.28–4.0, User-Defined', ...
        'User-defined spectral reflectance, Albedo, Lambertian, User-defined, User-Defined', ...
        'User-defined spectral reflectance, Albedo, Non-Lambertian, User-defined, User-Defined', ...
        'Water or calm ocean, (calculated), Spectral, 0.28–4.0, Water, snow, or ice', ...
        'Fresh dry snow, Snow, Non-Lambertian, 0.3–2.48, Water, snow, or ice', ...
        'Snow on a mountain neve, Neve, Non-Lambertian, 0.45–1.65, Water, snow, or ice', ...
        'Basalt rock, Basalt, Non-Lambertian, 0.3–2.48, Soils and rocks', ...
        'Dry sand, Dry_sand, Non-Lambertian, 0.32–0.99, Soils and rocks', ...
        'Sand from White Sands, NM, WiteSand, Non-Lambertian, 0.5–2.48, Soils and rocks', ...
        'Bare soil, Soil, Non-Lambertian, 0.28–4.0, Soils and rocks', ...
        'Dry clay soil, Dry_clay, Non-Lambertian, 0.5–2.48, Soils and rocks', ...
        'Wet clay soil,  Wet_clay, Non-Lambertian, 0.5–2.48, Soils and rocks', ...
        'Alfalfa,  Alfalfa, Non-Lambertian, 0.3–0.8, Vegetation', ...
        'Green grass, Grass, Non-Lambertian, 0.3–1.19, Vegetation', ...
        'Perennial rye grass, RyeGrass, Non-Lambertian, 0.44–2.28, Vegetation', ...
        'Alpine meadow, Meadow1, Non-Lambertian, 0.4–0.85, Vegetation', ...
        'Lush meadow, Meadow2, Non-Lambertian, 0.4–0.9, Vegetation', ...
        'Wheat crop, Wheat, Non-Lambertian, 0.42–2.26, Vegetation', ...
        'Ponderosa pine tree, PineTree, Non-Lambertian, 0.34–2.48, Vegetation', ...
        'Concrete slab, Concrete, Non-Lambertian, 0.3–1.3, Manmade materials', ...
        'Black loam, BlckLoam, Non-Lambertian, 0.4–4.0, Soils and rocks', ...
        'Brown loam, BrwnLoam, Non-Lambertian, 0.4–4.0, Soils and rocks', ...
        'Brown sand, BrwnSand, Non-Lambertian, 0.4–4.0, Soils and rocks', ...
        'Conifer trees, Conifers, Non-Lambertian, 0.302–4.0, Vegetation', ...
        'Dark loam, DarkLoam, Non-Lambertian, 0.46-4.0, Soils and rocks', ...
        'Dark sand, DarkSand, Non-Lambertian, 0.4–4.0, Soils and rocks', ...
        'Decidous trees, Decidous, Non-Lambertian, 0.302–4.0, Vegetation', ...
        'Dry grass (sod), DryGrass, Non-Lambertian, 0.38–4.0, Vegetation', ...
        'Dune sand, DuneSand, Non-Lambertian, 0.4–4.0, Soils and rocks', ...
        'Fresh fine snow, FineSnow, Non-Lambertian, 0.3–4.0, Water, snow, or ice', ...
        'Green rye grass (sod), GrnGrass, Non-Lambertian, 0.302–4.0, Vegetation', ...
        'Granular snow, GrnlSnow, Non-Lambertian, 0.3–4.0, Water, snow, or ice', ...
        'Light clay, LiteClay, Non-Lambertian, 0.4–4.0, Soils and rocks', ...
        'Light loam, LiteLoam, Non-Lambertian, 0.431–4.0, Soils and rocks', ...
        'Light sand, LiteSand, Non-Lambertian, 0.4–4.0, Soils and rocks', ...
        'Pale loam, PaleLoam, Non-Lambertian, 0.4–4.0, Soils and rocks', ...
        'Sea water, Seawater, Non-Lambertian, 2.079–4.0, Water, snow, or ice', ...
        'Solid ice, SolidIce, Non-Lambertian, 0.3–4.0, Water, snow, or ice', ...
        'Dry soil, Dry_Soil, Non-Lambertian, 0.28–4.0, Soils and rocks', ...
        'Light soil, LiteSoil, Non-Lambertian, 0.28–4.0, Soils and rocks', ...
        'Old runway concrete, RConcrte, Non-Lambertian, 0.3–4.0, Manmade materials', ...
        'Old runway asphalt, Asphalt, Non-Lambertian, 0.3–4.0, Manmade materials', ...
        'Terracota roofing clay tile, RoofTile, Non-Lambertian, 0.3–4.0, Manmade materials', ...
        'Red construction brick, RedBrick, Non-Lambertian, 0.3–4.0, Manmade materials', ...
        'Gravel, Gravel, Non-Lambertian, 0.32-1.3, Soils and rocks', ...
        'Sand & gravel, SndGravl, Non-Lambertian, 0.45-1.04, Soils and rocks', ...
        'Fallow field, Fallow, Non-Lambertian, 0.32-1.19, Soils and rocks', ...
        'Tall green corn, TallCorn, Non-Lambertian, 0.36-1.0, Vegetation', ...
        'Birch leaves, Birch, Non-Lambertian, 0.36-2.48, Vegetation', ...
        'Wet sandy soil, WetSSoil, Non-Lambertian, 0.48-2.48, Soils and rocks', ...
        'Wet red clay, WetClay2, Non-Lambertian, 0.52-2.48, Soils and rocks', ...
        'Wet silt, WetSilt, Non-Lambertian, 0.52-2.48, Soils and rocks', ...
        'Dry long grass, LngGrass, Non-Lambertian, 0.52-2.48, Vegetation', ...
        'Lawn grass (generic bluegrass), LwnGrass, Non-Lambertian, 0.277-2.976, Vegetation', ...
        'Decidous oak tree leaves, OakTree, Non-Lambertian, 0.305-2.944, Vegetation', ...
        'Pinion pintetree needles, Pinion, Non-Lambertian, 0.35-2.5, Vegetation', ...
        'Melting snow (slush), MeltSnow, Non-Lambertian, 0.301-2.592, Water, snow, or ice', ...
        'Plywood sheet (new, pine, 4-ply), Plywood, Non-Lambertian, 0.35-2.5, Manmade materials', ...
        'White vinyl plastic sheet, 0.15 mm, WiteVinl, Non-Lambertian, 0.35-2.5, Manmade materials', ...
        'Clear fiberglass greenhouse roofing, FibrGlss, Non-Lambertian, 0.35-2.5, Manmade materials', ...
        'Galvanized corrugated sheet metal, new, ShtMetal, Non-Lambertian, 0.35-2.5, Manmade materials', ...
        'Wetland vegetation canopy, Yellowstone, Wetland, Non-Lambertian, 0.409-2.478, Vegetation', ...
        'Sagebrush canopy, Yellowstone, SageBrsh, Non-Lambertian, 0.409-2.478, Vegetation', ...
        'Fir trees, Colorado, FirTrees, Non-Lambertian, 0.353-2.592, Vegetation', ...
        'Coastal seawater, Pacific, CSeaWatr, Non-Lambertian, 0.277-2.976,Water, snow, or ice', ...
        'Open ocean seawater, Atlantic, OSeaWatr, Non-Lambertian, 0.277-2.976, Water, snow, or ice', ...
        'Grazing field (unfertilized), GrazingField, Non-Lambertian, 0.401-2.499, Vegetation', ...
        'Young Norway spruce tree (needles), Spruce, Non-Lambertian, 0.39-0.845, Vegetation' ...
            };

    end

    methods

        function far_field_albedo = far_field_albedo(varargin)
            % NOTE: defaults?
            % should default behaviour here be to set ialbdg == spectral_reflectance
            % if no value for ialbdg is supplied?

            far_field_albedo.flag = 0;
            far_field_albedo.card_type = 'IALBDX';
            far_field_albedo.card_num = 10;

            far_field_albedo.groups = {{}, ...
                {'zonal_broadband_albedo'}, ...
                ...
                {   {'zonal_broadband_albedo'}, ...
                    {'tilt'}, ...
                    {'local_foreground_albedo', 'tilt_degree', 'azimuth'}, ...
                }, ...
                ...
                {   {'zonal_broadband_albedo'}, ...
                    {'tilt'}, ...
                    {'local_foreground_albedo', 'tilt_degree', 'azimuth'}, ...
                    {'local_background_albedo'}...
                }, ...
                ...
                {   {'tilt'}, ...
                    {'local_foreground_albedo', 'tilt_degree', 'azimuth'}, ...
                }, ...
                ...
                {   {'tilt'}, ...
                    {'local_foreground_albedo', 'tilt_degree', 'azimuth'}, ...
                    {'local_background_albedo'}...
                } ...
                };

            far_field_albedo.suffix = {'', ...
                                       'a', ...
                                       {'a', 'b', 'c'}, ...
                                       {'a', 'b', 'c', 'd'}, ...
                                       {'b', 'c'}, ...
                                       {'b', 'c', 'd'} ...
                                    };

            p = inputParser;
            addParameter(p, 'spectral_reflectance', nan);
            addParameter(p, 'rhox', nan);
            addParameter(p, 'ialbdg', nan);
            addParameter(p, 'tilt', nan);
            addParameter(p, 'wazim', nan);
            addParameter(p, 'rhog', nan);

            parse(p, varargin{:});

            assert(p.Results.spectral_reflectance >= -1, ...
                   '"spectral_reflectance" must be between -1 and 66');

            assert(p.Results.spectral_reflectance <= 66, ...
                   '"spectral_reflectance" must be between -1 and 66');

            assert(~isinteger(p.Results.spectral_reflectance), ...
                   '"spectral_reflectance" must an integer');

            far_field_albedo.spectral_reflectance = p.Results.spectral_reflectance;
            far_field_albedo.amount = p.Results.spectral_reflectance;
            far_field_albedo.flag = 1;

            if -1 == p.Results.spectral_reflectance
                assert(~isnan(p.Results.rhox), ...
                    'if "spectral_reflectance" == -1, "rhox" must be set');
                far_field_albedo.flag = far_field_albedo.flag + 1;
                far_field_albedo.zonal_broadband_albedo = p.Results.rhox;

                if isnan(p.Results.rhox)
                    far_field_albedo.flag = 4;
                end
            end

            if (-1 ~= p.Results.spectral_reflectance) & ~isnan(p.Results.tilt)
                far_field_albedo.flag = 4;
            end

            if ~isnan(p.Results.tilt)
                far_field_albedo.tilt = 1;
                assert(~isnan(p.Results.wazim), ...
                    '"wazim" must be set if tilt is');
                assert(~isnan(p.Results.ialbdg), ...
                    '"wazim" and "tilt" then "ialbdg" must be set');

                far_field_albedo.flag = far_field_albedo.flag + 1;
                far_field_albedo.tilt_degree = p.Results.tilt;
                far_field_albedo.azimuth = p.Results.wazim;
                far_field_albedo.local_foreground_albedo = p.Results.ialbdg;

                if -1 == p.Results.ialbdg
                    assert(~isnan(p.Results.rhog), ...
                        'if "ialbdg" == -1, rhog must be set');
                    far_field_albedo.flag = far_field_albedo.flag + 1;
                    far_field_albedo.local_background_albedo = p.Results.rhog;
                end
            end

            far_field_albedo.flag = far_field_albedo.flag - 1;

        end


        function show_options(far_field_albedo)
            for i = 1 : length(far_field_albedo.albedo_opts)
                disp([num2str(i), ':', char(9), far_field_albedo.albedo_opts{i}]);
            end
        end

    end

end



