function result = loadPreset(preset)
    arguments (Input)
        preset {mustBeMember( preset, { ...
            'Excelitas', 'Hamamatsu', ...
            'LaserComponents', 'MicroPhotonDevices', ...
            'PerkinElmer', 'ID_Qube_NIR', ...
            'QuantumOpus_RoomTemperatureAmplifier', ...
            'QuantumOpus_CryogenicAmplifier', ...
            })}
    end

    [path, ~] = fileparts(which('detectors.loadPreset'));
    %file_path = strjoin(path, ); %, "presets", filesep, preset, ".mat"];
    file_name = strjoin([preset, 'mat'], ".");
    file_path = strjoin([path, 'presets', file_name], filesep);
    disp(file_path)
    result = detectors.DetectorPresetBuilder().loadPreset(file_path);
end
