function loaded = loadPreset(preset)
    arguments (Input)
        preset {mustBeMember( preset, { ...
            'Excelitas', 'Hamamatsu', ...
            'LaserComponents', 'MicroPhotonDevices', ...
            'PerkinElmer', 'ID_Qube_NIR', ...
            'QuantumOpus_RoomTemperatureAmplifier', ...
            'QuantumOpus_CryogenicAmplifier', ...
            })}
    end

    [path, ~] = fileparts(which('sensors.detectors.loadPreset'));
    file_path = [path, [filesep, 'presets', filesep, preset, '.mat']];
    loaded = sensors.detectors.DetectorPresetBuilder().loadPreset(file_path);
end
