% a simulation of a decoy BB84 satellite pass which implements beacon simulations
% alongside the quantum channel

%% 1. Choose parameters
wavelength=785;                                                            %wavelength is measured in nm
transmitter_telescope_diameter=0.1;                                        %diameters are measured in m
orbit_data_file_location='500kmSSOrbitLLAT.txt';                              %orbits are described by files containing latitude, longitude, altitude and time stamps. These are in the 'orbit modelling resources' folder
receiver_telescope_diameter=1;                                           
time_gate_width=1E-9;                                                      %times are measured in s
spectral_filter_width=10;                                                  %consistemt with wavelength, spectral width is measured in nm
repetition_rate = 1E9;                                                     %repetition rate in Hz
beacon_power = 1;                                                           %beacon power in W
beacon_wavelength = 850;                                                    %beacon wavelength in nm
downlink_beacon_divergence = 1E-3;                                         %beacon divergence in rads
open_loop_pointing_precision = 1E-3;                                 %rms pointing error in rads
uplink_beacon_divergence = 1E-5;                                           %beacon divergence in rads
closed_loop_pointing_precision = 1E-6;                                   %rms pointing error in rads
ogs_camera_scope_diameter = 0.4;                                                %camera telescope diameter in m
camera_exposure_time = 0.001;                                              %exposure time of beacon cameras in s
beacon_camera_filter_width = 10;                                           %camera spectral filter width in nm
Env = environment.Environment.load("Examples\Data\atmospheric transmittance\Dark Environment 10km.mat"); %use an assumed 10km visibility 
%% 2. Construct components

%2.1 Satellite
%2.1.1 Source
Transmitter_Source=components.Source(wavelength,"Repetition_Rate",repetition_rate,...
                                     "MPN_Signal",0.7,"MPN_Decoy",0.3,...
                                     "Probability_Signal",0.75,"Probability_Decoy",0.2);%we use default values to simplify this example

%2.1.2 Transmitter telescope
Transmitter_Telescope=components.Telescope(transmitter_telescope_diameter,...
                                           "Wavelength",wavelength,...
                                           'Pointing_Jitter',closed_loop_pointing_precision); %do not need to specify wavelength as this will be set by satellite object

%2.1.3 Satellite downlink beacon
Downlink_Beacon_Telescope = setWavelength(Transmitter_Telescope,beacon_wavelength);
Downlink_Beacon = beacon.GaussianBeacon(Downlink_Beacon_Telescope,...
                                        beacon_power,...
                                        beacon_wavelength,...
                                        'Divergence_Half_Angle',downlink_beacon_divergence/2,...
                                        'Pointing_Jitter',open_loop_pointing_precision);

%2.1.4 add a beacon camera to the satellite
Uplink_Cam = CVM4000(Transmitter_Telescope, ...
                     camera_exposure_time,...
                     beacon_camera_filter_width);

%2.1.5 Construct satellite
SimSatellite=nodes.Satellite(Transmitter_Telescope,...
                            'OrbitDataFileLocation',orbit_data_file_location,...
                            'Source',Transmitter_Source,...
                            'Beacon',Downlink_Beacon,...
                            'Camera',Uplink_Cam,...
                            'Name','ExampleSat');

%2.2 Ground station
%2.2.1 Detector
Det=components.Detector(wavelength, ...
             repetition_rate,...
             time_gate_width,...
             spectral_filter_width,...
             'Preset','MicroPhotonDevices');
%need to provide repetition rate in order to compute QBER and loss due to
%time gating

%2.2.2 Receiver telescope
Receiver_Telescope=components.Telescope(receiver_telescope_diameter,...
                                        "Wavelength",wavelength,...
                                        'Pointing_Jitter',closed_loop_pointing_precision);

%2.2.3 add a beacon camera to the ground station
Downlink_Camera_Scope = components.Telescope(ogs_camera_scope_diameter,'Wavelength',beacon_wavelength);
Downlink_Cam = ATIK(Downlink_Camera_Scope,...
                    camera_exposure_time,...
                    beacon_camera_filter_width);

%2.2.4 Ground station uplink beacon
Uplink_Beacon_Scope = setWavelength(Receiver_Telescope,beacon_wavelength);
Uplink_Beacon = beacon.GaussianBeacon(Uplink_Beacon_Scope,...
                                       beacon_power,...
                                       beacon_wavelength,...
                                       'Divergence_Half_Angle',uplink_beacon_divergence,...
                                       'Pointing_Jitter',closed_loop_pointing_precision);

%2.2.5 construct ground station, use Heriot-Watt as an example
SimGround_Station = nodes.GroundStation(Receiver_Telescope,...
                                       'Detector',Det,...
                                       'LLA',[55.909723, -3.319995,10],...
                                       'Name','Heriot-Watt',...
                                       'Beacon',Uplink_Beacon,...
                                       'Camera',Downlink_Cam,...
                                       'Environment',Env);

%% 3 Compose and run the PassSimulation
%3.1 run simulation
Result = nodes.qkdPassSimulation(SimGround_Station,SimSatellite,protocol.DecoyBB84);
DownlinkBeaconResults = beacon.beaconSimulation(SimGround_Station,SimSatellite);
UplinkBeaconResults = beacon.beaconSimulation(SimSatellite,SimGround_Station);
%3.2 plot results
plot(Result);
plot(DownlinkBeaconResults);
plot(UplinkBeaconResults);

