function hogs = HubOpticalGroundStation(wavelength, repetition_rate, time_gate)
    arguments
        wavelength {mustBeNumeric}
        repetition_rate {mustBeNumeric} = 1e8
        time_gate {mustBeNumeric} = 2e-9
    end

    telescope = components.Telescope( ...
        0.7, ...
        Pointing_Jitter       = 1e-6, ...
        Optical_Efficiency    = (1 - 0.3 ^ 2) * 10^(-1.1 / 10), ...
        Focal_Length          = 8.4, ...
        Eyepiece_Focal_Length = 0.076);

    spectral_filter = components.IdealBPFilter(wavelength, 3);

    detector = components.Detector(wavelength, repetition_rate, ...
        time_gate, spectral_filter, ...
        Preset = components.loadPreset("Excelitas") );

    camera_telescope = components.Telescope( ...
        0.4, ...
        Wavelength = 685, ...
        Optical_Efficiency = 1 - 0.39^2, ...
        Focal_Length = 2.72, ...
        Pointing_Jitter = 1e-3);

    exposure_time = 0.01;
    spectral_filter_width = 10;
    camera = AC4040(camera_telescope, exposure_time, spectral_filter_width);

    beacon_power = 40E-3;
    beacon_wavelength = 850;
    beacon_pointing_precision = 1E-6;
    beacon_beam_divergence = 0.0070;
    beacon_telescope = SetWavelength(telescope, beacon_wavelength);
    beacon_telescope = SetFOV(beacon_telescope, beacon_beam_divergence);
    beacon_efficiency = 1;
    gaussian_beacon = beacon.Gaussian_Beacon( ...
        beacon_telescope, beacon_power, beacon_wavelength,...
        Power_Efficiency = beacon_efficiency, ...
        Pointing_Jitter = beacon_pointing_precision);

    hogs = nodes.Ground_Station( ...
        telescope, ...
        Detector = detector,                   ...
        Camera   = camera,     ...
        Beacon   = gaussian_beacon, ...
        LLA      = [55.909723, -3.319995, 10], ...
        name     = 'Heriot Watt');

end

