function OWL320HS = OWL320HS(Telescope,Exposure_Time,Spectral_Filter_Width)
%Raptor photonics OWL320HS camera object constructor

%exposure time in s
%spectral filter width in nm



OWL320HS = beacon.Camera(Telescope,...
            'Quantum_Efficiency',0.45,...
            'Exposure_Time', Exposure_Time,...
            'Spectral_Filter_Width',Spectral_Filter_Width,...
            'Detector_Diameter',0.00768,...
            'Focal_Length', 0.0125,...
            'Readout_Noise', 202,...
            'Dark_Current', 0,...
            'Full_Well_Capacity', 170E3,...
            'Pixels',[320,256]);
end

