function AC4040 = AC4040(Telescope,Exposure_Time,Spectral_Filter_Width)
%Diffraction limited AC4040 camera object constructor
%this camera uses the Gsense 4040 chip: https://www.gpixel.com/products/area-scan-en/gsense/gsense4040/
%exposure time in s
%spectral filter width in nm



AC4040 = beacon.Camera(Telescope,...
            'Quantum_Efficiency',0.74,...
            'Exposure_Time', Exposure_Time,...
            'Spectral_Filter_Width',Spectral_Filter_Width,...
            'Detector_Diameter',0.0368,...
            'Focal_Length', 0.0125,...
            'Readout_Noise', 3.7,...
            'Dark_Current', 12.2,...
            'Full_Well_Capacity', 74000,...
            'Pixels',[4096,4096]);
end

