function ATIKCamera = ATIK()
%ATIK camera object type


%% telescope
Telescope_Diameter = 0.25;                                                      %telescope diameter in m, used to calculate collecting area
Beacon_Telescope_Efficiency = 0.9;                                              %efficiency of beacon telescope optical path
Camera_Scope = Telescope(Telescope_Diameter,...
    'Optical_Efficiency',Beacon_Telescope_Efficiency);


ATIKCamera = Camera(Camera_Scope,...
            'Quantum_Efficiency',1,...
            'Exposure_Time', 0.001,...
            'Spectral_Filter_Width',10,...
            'Detector_Diameter',0.0017,...
            'Focal_Length', 0.0125,...
            'Readout_Noise', 2.4,...
            'Dark_Current', 0.027,...
            'Full_Well_Capacity', 11E3);
end

