function ATIKCamera = ATIK(Exposure_Time,Spectral_Filter_Width)
%ATIK camera object constructor

%exposure time in s
%spectral filter width in nm

%% telescope
Telescope_Diameter = 0.25;                                                      %telescope diameter in m, used to calculate collecting area
Beacon_Telescope_Efficiency = 0.9;                                              %efficiency of beacon telescope optical path
Camera_Scope = Telescope(Telescope_Diameter,...
    'Optical_Efficiency',Beacon_Telescope_Efficiency);


ATIKCamera = Camera(Camera_Scope,...
            'Quantum_Efficiency',1,...
            'Exposure_Time', Exposure_Time,...
            'Spectral_Filter_Width',Spectral_Filter_Width,...
            'Detector_Diameter',0.0017,...
            'Focal_Length', 0.0125,...
            'Readout_Noise', 1.3E-11,...
            'Dark_Current', 0,...
            'Full_Well_Capacity', 2E-9);
end

