function SatCamera = CVM4000(Telescope,Exposure_Time,Spectral_Filter_Width)
%CVM4000-based camera object camera object constructor
% https://ams.com/documents/20143/36005/CMV4000_DS000728_5-00.pdf

%exposure time in s
%spectral filter width in nm

SatCamera = beacon.Camera(Telescope,...
            'Quantum_Efficiency',0.35*0.42,...
            'Exposure_Time', Exposure_Time,...
            'Spectral_Filter_Width',Spectral_Filter_Width,...
            'Detector_Diameter',0.015,...
            'Focal_Length', 0.0125,...
            'Readout_Noise', 13,...
            'Dark_Current', 125,...
            'Full_Well_Capacity', 13500,...
            'Pixels',[2048,2048]);
end

