%% run
close all
clear all

ContentsOfDirectory = @(DirPath) {dir(adduserpath(DirPath)).name};

FilterFiles = @(DirectoryContents, Query) ...
    {DirectoryContents{cellfun( ...
        @(fp) contains(fp, Query), ...
        DirectoryContents)} ...
    };

in_target_path = '~/Documents/tqi_data/matfiles/';

in_radianceFiles = FilterFiles( ...
    ContentsOfDirectory(in_target_path), ...
    '__radiance');

disp(in_radianceFiles')

jan_rf = radiance_file([in_target_path, in_radianceFiles{4}]);
aug_rf = radiance_file([in_target_path, in_radianceFiles{3}]);

%% Plot January

figure
wvl = 850;
[ff, c] = polarpcolor( ...
    jan_rf.azimuths, ...
    rad2deg(jan_rf.elevations), ...
    fliplr(jan_rf.pickRadianceForWavelength(wvl)) ...
);
c.Label.String = '$mW/sr/m^2$'
c.Label.Interpreter = 'latex';
c.TickLabelInterpreter = 'latex';
exportgraphics(gcf, ...
    adduserpath([ ...
    '~/Documents/tqi_review_march_2023/src/figures/radiance_jan_0900_', ...
    num2str(wvl), ...
    '.pdf']), ...
    'ContentType','vector')

figure
wvl = 1550;
[ff, c] = polarpcolor( ...
    jan_rf.azimuths, ...
    rad2deg(jan_rf.elevations), ...
    fliplr(jan_rf.pickRadianceForWavelength(wvl)) ...
);
c.Label.String = '$mW/sr/m^2$'
c.Label.Interpreter = 'latex';
c.TickLabelInterpreter = 'latex';
exportgraphics(gcf, ...
    adduserpath([ ...
    '~/Documents/tqi_review_march_2023/src/figures/radiance_jan_0900_', ...
    num2str(wvl), ...
    '.pdf']), ...
    'ContentType','vector')

%% Plot August

figure
wvl = 850;
[ff, c] = polarpcolor( ...
    aug_rf.azimuths, ...
    rad2deg(aug_rf.elevations), ...
    fliplr(aug_rf.pickRadianceForWavelength(wvl)) ...
);
c.Label.String = '$mW/sr/m^2$'
c.Label.Interpreter = 'latex';
c.TickLabelInterpreter = 'latex';
exportgraphics(gcf, ...
    adduserpath([ ...
    '~/Documents/tqi_review_march_2023/src/figures/radiance_aug_1500_', ...
    num2str(wvl), ...
    '.pdf']), ...
    'ContentType','vector')

figure
wvl = 1550;
[ff, c] = polarpcolor( ...
    aug_rf.azimuths, ...
    rad2deg(aug_rf.elevations), ...
    fliplr(aug_rf.pickRadianceForWavelength(wvl)) ...
);
c.Label.String = '$mW/sr/m^2$'
c.Label.Interpreter = 'latex';
c.TickLabelInterpreter = 'latex';
exportgraphics(gcf, ...
    adduserpath([ ...
    '~/Documents/tqi_review_march_2023/src/figures/radiance_aug_1500_', ...
    num2str(wvl), ...
    '.pdf']), ...
    'ContentType','vector')

