function true_anomaly = eccentricity2trueAnomaly(eccentricity)
    true_anomaly = 2 .* atan(...
        sqrt(...
        (1 + eccentricity) ...
        / (1 - eccentricity)) ...
        .* tan(eccentricity / 2));
end
