% Get the property from "obj" that is the same type/class as stated in the target string "target"
function property = getPropertyFromObject(obj, target)

    arguments
        obj
        target {mustBeText}
    end

    props = properties(obj);
    checks = cell2mat( ...
        cellfun( ...
            @(prop) isa(obj.(prop), target), ...
            props, ...
            UniformOutput=false) );

    if ~any(checks == true)
        error(...
             'utilities:getPropertyFromObject', ...
            'No property of type %s in %s', target, inputname(1));
    end

    property = obj.( ...
        string(props(cell2mat(cellfun( ...
            @(prop) isa(obj.(prop), target), ...
            props, ...
            UniformOutput=false) ...
            ))) ...
        );
end

